services:
  qemu:
    container_name: qemu
    image: qemux/qemu-docker
    environment:
      BOOT: "https://enterprise.proxmox.com/iso/proxmox-ve_8.2-2.iso"
    devices:
      - /dev/kvm
    volumes:
      - /mnt/storage
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
    stop_grace_period: 2m
