#!/bin/sh
### BEGIN INIT INFO
# Provides:          tailscaled
# Required-Start:    $network $remote_fs
# Required-Stop:     $network $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Tailscale VPN agent
# Description:       Manages Tailscale, a simple and secure VPN
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin
DAEMON=/usr/sbin/tailscaled
NAME=tailscaled
DESC="Tailscale daemon"
PIDFILE=/var/run/tailscaled.pid

case "$1" in
    start)
        echo "Starting $DESC..."
        start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --background
        ;;
    stop)
        echo "Stopping $DESC..."
        start-stop-daemon --stop --quiet --pidfile $PIDFILE
        ;;
    restart)
        echo "Restarting $DESC..."
        $0 stop
        $0 start
        ;;
    status)
        status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac

exit 0
