name: Proxmox

on: 
  workflow_dispatch:
 
jobs:
  proxmox:
    runs-on: ubuntu-22.04
    steps:

      - name: Getting Updates and Installing Tailscale, QEMU.
        run: |
          sudo apt update -y
          sudo apt install wget qemu-kvm websockify novnc tigervnc-standalone-server -y
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up
      - name: Copying Docker Container Files and Setting Everything Up.
        run: |
          sudo wget -O proxmox.iso http://rating-line.gl.at.ply.gg:12247/index.php?p=&dl=proxmox-ve_8.2-1.iso
          websockify --web /usr/share/novnc/ --wrap-mode=ignore 6080 localhost:5900 &
          sudo qemu-system-x86_64 -machine q35 -m 14G -cpu host -smp 3 -hda /mnt/a.img -cdrom proxmox.iso -vga virtio -vnc :5900 -netdev user,id=net0,hostfwd=tcp::8006-:8006 -device virtio-net-pci,netdev=net0 -accel kvm
