name: Proxmox (Docker)

on: 
  workflow_dispatch:
 
jobs:
  proxmox:
    runs-on: ubuntu-22.04
    steps:

      - name: Getting Updates and Installing Tailscale, Docker.
        run: |
          sudo apt update -y
          sudo apt install aria2 docker.io websockify novnc tigervnc-standalone-server -y
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --ssh
      - name: Copying Docker Container Files and Setting Everything Up.
        run: |
          sudo aria2c -s16 -x16 https://github.com/Efebey2903/Proxmox/releases/download/proxmox/proxmox.iso
          sudo qemu-img create -f raw /mnt/a.img 127G
          websockify --web /usr/share/novnc/ --wrap-mode=ignore 6080 localhost:5900 &
          sleep 2
          wget -O docker-compose.yml https://pastebin.com/raw/SSXyzyiF
          wait
          docker-compose build
          sleep 3
          docker-compose up
