name: proxmox playit 

on: 
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Downloading and Installing Essentials.
        run: |
          sudo apt update -y
          sudo apt install qemu-kvm cpulimit wget -y
          curl -SsL https://playit-cloud.github.io/ppa/key.gpg | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/playit.gpg >/dev/null
          echo "deb [signed-by=/etc/apt/trusted.gpg.d/playit.gpg] https://playit-cloud.github.io/ppa/data ./" | sudo tee /etc/apt/sources.list.d/playit-cloud.list
          sudo apt update
          sudo apt install playit
      - name: Starting up Proxmox..
        run: |
          sudo chmod 666 /dev/kvm
          sudo qemu-img create -f qcow2 /mnt/a.qcow2 120G
          sudo qemu-img create -f raw a.img 16G
          while ps axg | grep -vw grep | grep -w wget > /dev/null; do sleep 1; done
          wget -O proxmox.iso https://github.com/Efebey2903/Proxmox/releases/download/proxmox/proxmox.iso &>/dev/null &
          while ps axg | grep -vw grep | grep -w wget > /dev/null; do sleep 1; done
          echo "go 6080 from browser"
          sudo cpulimit -l 99 -- sudo kvm -M q35,usb=on -device usb-tablet -cpu host -smp 3 -m 14G -device virtio-balloon-pci -vga qxl -netdev user,id=net0,hostfwd=tcp::8006-:8006 -device virtio-net-pci,netdev=net0 -enable-kvm -drive file=/mnt/a.qcow2,if=none,id=nvme0,format=raw -device nvme,drive=nvme0,serial=maycolenko,max_ioqpairs=8 -drive file=a.img,format=raw,id=stick,if=none -device nec-usb-xhci,id=xhci -device usb-storage,bus=xhci.0,drive=stick -drive file=proxmox.iso,media=cdrom  -vnc :0
          playit
          while ps axg | grep -vw grep | grep -w qemu-system-x86_64 > /dev/null; do sleep 1; done
          while ps axg | grep -vw grep | grep -w kvm > /dev/null; do sleep 1; done
